import type { Character, Ending } from "../types";

const endingImages: Record<string, string> = {
  "scorpio-normal": "/assets/ending-scorpio-normal.png",
  "capricorn-hidden": "/assets/ending-capricorn-hidden.png",
  "pisces-normal": "/assets/ending-pisces-normal.png",
  "pisces-hidden": "/assets/ending-pisces-hidden.png",
  "aries-bad": "/assets/ending-aries-bad.png",
  "aries-good": "/assets/ending-aries-good.png",
  "taurus-hidden": "/assets/ending-taurus-hidden.png",
};

const endingSet = (id: string, name: string): Ending[] => {
  const common = [
    {
      id: `${id}-bad`,
      characterId: id,
      type: "bad" as const,
      title: `${name} Bad Ending：錯過的星光`,
      description: "你們不是沒有心動，而是太早把對方放進自己的想像裡。誤會累積成沉默，最後只剩星盤上一條沒有抵達的線。",
      requirements: ["好感過低", "信任不足", "嫉妒或誤解過高"],
      imageUrl: endingImages[`${id}-bad`],
    },
    {
      id: `${id}-normal`,
      characterId: id,
      type: "normal" as const,
      title: `${name} Normal Ending：剛好的距離`,
      description: "故事停在朋友的位置。你們仍會在校園裡打招呼，但那句更靠近的話，被留給了另一個平行宇宙。",
      requirements: ["完成主線", "好感或信任未達戀愛線"],
      imageUrl: endingImages[`${id}-normal`],
    },
    {
      id: `${id}-good`,
      characterId: id,
      type: "good" as const,
      title: `${name} Good Ending：把喜歡說出口`,
      description: "你們學會在日常裡靠近，不急著證明命運，只把今天的心意好好放進彼此手裡。",
      requirements: ["好感 >= 65", "信任 >= 45", "嫉妒 < 70"],
      imageUrl: endingImages[`${id}-good`],
    },
    {
      id: `${id}-true`,
      characterId: id,
      type: "true" as const,
      title: `${name} True Ending：命運不是答案`,
      description: "你們理解了彼此最不想被看見的傷口。星座不是結論，只是你們終於願意走向對方的起點。",
      requirements: ["好感 >= 85", "信任 >= 75", "完成核心價值選項"],
    },
    {
      id: `${id}-career`,
      characterId: id,
      type: "career" as const,
      title: `${name} Career Ending：多年後的同行者`,
      description: "成年後，你們在各自道路上重逢。這一次，喜歡不再只是校園心動，也是一種能並肩前進的選擇。",
      requirements: ["成年後番外", "能力值與信任達標"],
    },
    {
      id: `${id}-hidden`,
      characterId: id,
      type: "hidden" as const,
      title: `${name} Hidden Ending：沒被星盤寫下的頁面`,
      description: "你觸發了他藏得最深的日常。那些沒有說出口的在意，終於變成只屬於你們的秘密結局。",
      requirements: ["觸發隱藏事件", "信任達標"],
      imageUrl: endingImages[`${id}-hidden`],
    },
  ];
  return common;
};

type CharacterSeed = Omit<
  Character,
  "affection" | "trust" | "jealousy" | "professorComposure" | "relationshipState" | "routeUnlocked" | "endings"
>;

const seeds: CharacterSeed[] = [
  {
    id: "aries",
    name: "夏燃",
    zodiac: "牡羊座",
    ageGroup: "高中生",
    schoolRole: "熱血籃球隊學長",
    adultRole: "創業公司 CEO",
    imageUrl: "/assets/aries-xia-ran.png",
    personality: "直接、衝動、保護慾強",
    hiddenTrait: "害怕自己只會往前衝，卻保護不了重要的人",
    likes: ["直球", "勇敢", "陪他挑戰"],
    dislikes: ["冷處理", "拐彎抹角"],
    difficulty: "★☆☆",
    keywords: ["籃球", "挑戰", "受傷"],
  },
  {
    id: "taurus",
    name: "陸雨田",
    zodiac: "金牛座",
    ageGroup: "高中生",
    schoolRole: "甜點社學長 / 家裡開咖啡廳",
    adultRole: "餐飲品牌老闆",
    imageUrl: "/assets/taurus-lu-yutian.png",
    personality: "慢熱、穩定、佔有慾細膩",
    hiddenTrait: "越重視越不敢開口，怕自己的心意變成壓力",
    likes: ["真誠", "陪伴", "記得小細節"],
    dislikes: ["忽冷忽熱", "浪費"],
    difficulty: "★☆☆",
    keywords: ["甜點", "陪伴", "限定蛋糕"],
  },
  {
    id: "gemini",
    name: "言澈",
    zodiac: "雙子座",
    ageGroup: "高中生",
    schoolRole: "廣播社人氣學弟",
    adultRole: "主持人 / 自媒體創作者",
    imageUrl: "/assets/gemini-yan-che.png",
    personality: "幽默、多話、難捉摸",
    hiddenTrait: "怕認真後被丟下，所以先把自己變成玩笑",
    likes: ["機智對話", "反差感", "有趣靈魂"],
    dislikes: ["無聊", "控制欲太強"],
    difficulty: "★★☆",
    keywords: ["廣播", "節奏", "玩笑背後"],
  },
  {
    id: "cancer",
    name: "沈泊安",
    zodiac: "巨蟹座",
    ageGroup: "高中生",
    schoolRole: "鄰家竹馬",
    adultRole: "兒科醫師 / 心理諮商師",
    imageUrl: "/assets/cancer-shen-boan.png",
    personality: "溫柔、顧家、情緒敏銳",
    hiddenTrait: "把吃醋藏進照顧裡，越難過越像沒事",
    likes: ["被依賴", "溫暖互動"],
    dislikes: ["被忽視", "尖銳拒絕"],
    difficulty: "★☆☆",
    keywords: ["竹馬", "安全感", "便當"],
  },
  {
    id: "leo",
    name: "盛陽",
    zodiac: "獅子座",
    ageGroup: "高中生",
    schoolRole: "學生會長 / 校園風雲人物",
    adultRole: "企業接班人 / 演藝圈製作人",
    imageUrl: "/assets/leo-sheng-yang.png",
    personality: "驕傲、華麗、需要被看見",
    hiddenTrait: "掌聲停下時會慌張，怕自己其實不值得被期待",
    likes: ["欣賞但不盲從", "舞台感"],
    dislikes: ["敷衍", "讓他丟臉"],
    difficulty: "★★☆",
    keywords: ["會長", "舞台", "光環裂縫"],
  },
  {
    id: "virgo",
    name: "顧硯",
    zodiac: "處女座",
    ageGroup: "高中生",
    schoolRole: "風紀委員 / 年級第一",
    adultRole: "研究員",
    imageUrl: "/assets/virgo-gu-yan.png",
    personality: "理性、挑剔、嘴硬",
    hiddenTrait: "嚴格其實是笨拙關心，怕鬆手就會失控",
    likes: ["努力", "守時", "細節控"],
    dislikes: ["混亂", "沒責任感"],
    difficulty: "★★★",
    keywords: ["補習", "規則", "嘴硬"],
  },
  {
    id: "libra",
    name: "白衡",
    zodiac: "天秤座",
    ageGroup: "高中生",
    schoolRole: "美術社學長 / 校草",
    adultRole: "設計師 / 藝術總監",
    imageUrl: "/assets/libra-su-lan.png",
    personality: "優雅、會社交、選擇困難",
    hiddenTrait: "總是照顧所有人的期待，卻不知道自己真正想要什麼",
    likes: ["審美", "氣質", "平衡感"],
    dislikes: ["粗魯", "情緒勒索"],
    difficulty: "★★☆",
    keywords: ["美術", "校草", "自我魅力"],
  },
  {
    id: "scorpio",
    name: "夜洵",
    zodiac: "天蠍座",
    ageGroup: "高中生",
    schoolRole: "神秘轉學生",
    adultRole: "律師 / 投資人",
    imageUrl: "/assets/scorpio-ling-shuo.png",
    personality: "深情、防備、佔有慾強",
    hiddenTrait: "轉學原因是一道傷口，他把信任看得比喜歡更重",
    likes: ["忠誠", "深度對話", "秘密交換"],
    dislikes: ["背叛", "試探"],
    difficulty: "★★★",
    keywords: ["秘密", "界線", "不能騙"],
  },
  {
    id: "sagittarius",
    name: "原野",
    zodiac: "射手座",
    ageGroup: "高中生",
    schoolRole: "交換學生 / 旅行社團成員",
    adultRole: "旅遊作家 / 攝影師",
    imageUrl: "/assets/sagittarius-jiang-ye.png",
    personality: "自由、開朗、不愛被綁住",
    hiddenTrait: "離開前最怕有人等他，因為那會讓自由變得很痛",
    likes: ["冒險", "幽默", "獨立"],
    dislikes: ["束縛", "查勤"],
    difficulty: "★★☆",
    keywords: ["旅行", "自由", "想回來"],
  },
  {
    id: "capricorn",
    name: "沈知衡",
    zodiac: "摩羯座",
    age: "32歲",
    ageGroup: "成年後",
    schoolRole: "成年後篇限定：國立大學物理系教授",
    adultRole: "凝態物理 / 量子材料實驗室 PI",
    title: "全校最難預約的教授",
    imageUrl: "/assets/capricorn-shen-zhiheng.png",
    personality: "冷靜、自律、外冷內熱",
    hiddenTrait: "全遊戲最容易吃醋、最沒有安全感，也最深情的人",
    likes: ["聰明", "有目標", "不黏人", "願意思考"],
    dislikes: ["說謊", "不守承諾", "浪費時間"],
    difficulty: "★★★",
    keywords: ["成年後", "物理教授", "冷靜值", "沒說出口的吃醋"],
  },
  {
    id: "aquarius",
    name: "藍祈",
    zodiac: "水瓶座",
    ageGroup: "高中生",
    schoolRole: "科學社怪才 / 程式天才",
    adultRole: "AI 工程師 / 發明家",
    imageUrl: "/assets/aquarius-lan-xu.png",
    personality: "怪、聰明、反套路",
    hiddenTrait: "用演算法包裝孤獨，怕被說奇怪所以先吐槽世界",
    likes: ["自由思考", "獨特觀點"],
    dislikes: ["從眾", "情緒勒索"],
    difficulty: "★★☆",
    keywords: ["演算法", "怪才", "吐槽"],
  },
  {
    id: "pisces",
    name: "霧島凜",
    zodiac: "雙魚座",
    ageGroup: "高中生",
    schoolRole: "音樂社學弟 / 夢幻系少年",
    adultRole: "音樂劇演員 / 作曲家",
    imageUrl: "/assets/pisces-yu-lan.png",
    personality: "浪漫、敏感、逃避現實",
    hiddenTrait: "怕夢想被現實判死刑，所以先假裝自己不在乎",
    likes: ["共感", "藝術", "溫柔鼓勵"],
    dislikes: ["冷漠", "過度打擊"],
    difficulty: "★☆☆",
    keywords: ["音樂", "夢想", "落地"],
  },
];

export const characters: Character[] = seeds.map((item) => ({
  ...item,
  affection: 0,
  trust: 0,
  jealousy: 0,
  professorComposure: 100,
  relationshipState: "stranger",
  routeUnlocked: false,
  endings: endingSet(item.id, item.name),
}));
